{
 "title": "Cluster State Board",
 "tags": [ "health" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Kubernetes health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum(machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Agentpool nodes number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_info{provider_id=~\".*hostpool.*\"})"
    }
   ]
  },
  {
   "title": "Agentpool nodes number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_info{provider_id=~\".*hostpool.*\"})"
    }
   ]
  },
  {
   "title": "Jupyter Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"jupyter-.*\"})"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum (machine_memory_bytes)" }
   ]
  },
  {
   "title": "Requested",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Cluster nodes network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "PVC free space",
   "type": "graph",
   "description": "PVC free space % of the total capacity.",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Cluster nodes available disk space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unavailable pods detailed",
   "type": "graph",
   "description": "Unavailable pods detailed",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas - kube_statefulset_status_replicas_ready > 0",
     "legendFormat": "{{statefulset}}"
    },
    {
     "expr": "label_replace(kube_replicaset_status_replicas - kube_replicaset_status_ready_replicas, \"my_replicaset\", \"$1\", \"replicaset\", \"(.*)-[^-]*\") > 0",
     "legendFormat": "{{my_replicaset}}"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable > 0",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  {
   "title": "Nodes problems",
   "type": "singlestat",
   "description": "Sum of nodes issues on conditions:\n- Ready = false\n- OutOfDisk = true\n- NetworkUnavailable = true\n- MemoryPressure = true\n- DiskPressure = true",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{condition=\"Ready\",status=\"false\"}) + sum (kube_node_status_condition{condition=\"OutOfDisk\",status=\"true\"}) + sum(kube_node_status_condition{condition=\"NetworkUnavailable\",status=\"true\"}) + sum (kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}) + sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "description": "Crashlooping Pods count",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[1h]) > 2 )"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "description": "Kubernetes unavailable pods",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_statefulset_status_replicas) + sum (kube_replicaset_status_replicas) + sum (kube_daemonset_status_number_unavailable) - sum (kube_statefulset_status_replicas_ready) - sum (kube_replicaset_status_ready_replicas)"
    }
   ]
  }
 ]
}