{
 "title": "Spark Metrics",
 "tags": [ "spark" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "appTag",
    "query": "label_values(kube_pod_labels, label_spark_app_tag)"
   },
   {
    "name": "appId",
    "query": "label_values(kube_pod_labels{label_spark_app_tag=\"$appTag\"}, label_spark_app_selector)"
   },
   {
    "name": "appName",
    "query": "label_values({job=\"$appId\"}, app_name)"
   },
   {
    "name": "podNamePrefix",
    "query": "label_values(kube_pod_labels{label_spark_app_selector=\"$appId\"}, pod)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{pod=~\"$podNamePrefix.*\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requested Executors Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"test\", created_by_name=~\"$podNamePrefix.*\"})"
    }
   ]
  },
  {
   "title": "Loki Log Links",
   "type": "text",
   "description": "Links to Loki Log Explore",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "content": "\n- [Driver](/grafana/explore?left=%5B%22now-6h%22,%22now%22,%22loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22$namespace%2F$podNamePrefix-driver%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)\n- [Executors](/grafana/explore?left=%5B%22now-6h%22,%22now%22,%22loki%22,%7B%22expr%22:%22%7Bspark_app_tag%3D%5C%22$appTag%5C%22,%20spark_exec_id%3D%5C%221%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)\n\n\n\n"
  },
  {
   "title": "Job Runtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{app_name=\"$appName\", job=\"$appId\", role=\"driver\"}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_executor_threadpool_activeTasks_Value{app_name=\"$appName\", job=\"$appId\"})"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_executor_threadpool_completeTasks_Value{app_name=\"$appName\", job=\"$appId\"})"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{app_name=\"$appName\", job=\"$appId\"} / java_lang_Memory_HeapMemoryUsage_max{app_name=\"$appName\", job=\"$appId\"}",
     "legendFormat": "{{role}}-{{number}}"
    }
   ]
  },
  {
   "title": "OS CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{app_name=\"$appName\", job=\"$appId\"} + java_lang_OperatingSystem_SystemCpuLoad{app_name=\"$appName\", job=\"$appId\"}",
     "legendFormat": "{{role}}-{{number}}"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{app_name=\"$appName\", job=\"$appId\"}",
     "legendFormat": "{{role}}-{{number}}"
    }
   ]
  },
  {
   "title": "Executor Threadpool Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spark_executor_threadpool_currentPool_size_Value{app_name=\"$appName\", job=\"$appId\", role=\"executor\"} / spark_executor_threadpool_maxPool_size_Value{app_name=\"$appName\", job=\"$appId\", role=\"executor\"}",
     "legendFormat": "exec-{{number}}"
    }
   ]
  },
  {
   "title": "Job Stages Metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_DAGScheduler_stage_runningStages_Value{app_name=\"$appName\", job=\"$appId\", role=\"driver\"}",
     "legendFormat": "runningStages"
    },
    {
     "expr": "spark_driver_DAGScheduler_stage_waitingStages_Value{app_name=\"$appName\", job=\"$appId\", role=\"driver\"}",
     "legendFormat": "waitingStages"
    },
    {
     "expr": "spark_driver_DAGScheduler_stage_failedStages_Value{app_name=\"$appName\", job=\"$appId\", role=\"driver\"}",
     "legendFormat": "failedStages"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_executor_threadpool_activeTasks_Value{app_name=\"$appName\", job=\"$appId\", role=\"executor\"}",
     "legendFormat": "{{role}}-{{number}}"
    }
   ]
  },
  {
   "title": "Test Custom Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spark_driver_custom_errorCount_Count{app_name=\"$appName\", job=\"$appId\", role=\"driver\"} / ignoring (column) group_left spark_driver_custom_inputCount_Count{app_name=\"$appName\", job=\"$appId\", role=\"driver\"}",
     "legendFormat": "{{table}}-{{column}}"
    }
   ]
  }
 ]
}